// <auto-generated />
using System;
using Libarary.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Libarary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Libarary.Models.Books.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotabkeWorks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorID");

                    b.ToTable("authors");
                });

            modelBuilder.Entity("Libarary.Models.Books.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<int>("ISBN")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PublicationYear")
                        .HasColumnType("date");

                    b.Property<int>("PublisherID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("BookID");

                    b.HasIndex("GenreID");

                    b.HasIndex("PublisherID");

                    b.ToTable("books");
                });

            modelBuilder.Entity("Libarary.Models.Books.BookAuthor", b =>
                {
                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.HasKey("BookID", "AuthorID");

                    b.HasIndex("AuthorID");

                    b.ToTable("booksAuthors");
                });

            modelBuilder.Entity("Libarary.Models.Books.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreID");

                    b.ToTable("genres");
                });

            modelBuilder.Entity("Libarary.Models.Books.Publisher", b =>
                {
                    b.Property<int>("PublisherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublisherID"));

                    b.Property<string>("ContactDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PublisherID");

                    b.ToTable("publishers");
                });

            modelBuilder.Entity("Libarary.Models.Libarary_system.LibararyBranche", b =>
                {
                    b.Property<int>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchID");

                    b.ToTable("LibararyBranches");
                });

            modelBuilder.Entity("Libarary.Models.Libarary_system.LibraryMember", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactDetalis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Membership")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberID");

                    b.ToTable("libraryMembers");
                });

            modelBuilder.Entity("Libarary.Models.Libarary_system.LibraryStaff", b =>
                {
                    b.Property<int>("StuffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StuffID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("StuffID");

                    b.ToTable("libraryStaffs");
                });

            modelBuilder.Entity("Libarary.Models.Storage.BookStorage", b =>
                {
                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("LibararyBrancheBranchID")
                        .HasColumnType("int");

                    b.HasKey("BookID", "BranchID");

                    b.HasIndex("LibararyBrancheBranchID");

                    b.ToTable("bookStorages");
                });

            modelBuilder.Entity("Libarary.Models.Trans.TransactionRecord", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<decimal>("Penalties")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StuffID")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.HasIndex("BookID");

                    b.HasIndex("MemberID");

                    b.HasIndex("StuffID");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("Libarary.Models.Books.Book", b =>
                {
                    b.HasOne("Libarary.Models.Books.Genre", "Genre")
                        .WithMany("book")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Libarary.Models.Books.Publisher", "Publisher")
                        .WithMany("book")
                        .HasForeignKey("PublisherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Libarary.Models.Books.BookAuthor", b =>
                {
                    b.HasOne("Libarary.Models.Books.Author", "Author")
                        .WithMany("bookAuthor")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Libarary.Models.Books.Book", "Book")
                        .WithMany("bookAuthors")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Libarary.Models.Storage.BookStorage", b =>
                {
                    b.HasOne("Libarary.Models.Books.Book", "Book")
                        .WithMany("bookStorages")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Libarary.Models.Libarary_system.LibararyBranche", "LibararyBranche")
                        .WithMany("bookStorages")
                        .HasForeignKey("LibararyBrancheBranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("LibararyBranche");
                });

            modelBuilder.Entity("Libarary.Models.Trans.TransactionRecord", b =>
                {
                    b.HasOne("Libarary.Models.Books.Book", "Book")
                        .WithMany("transaction")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Libarary.Models.Libarary_system.LibraryMember", "LibraryMember")
                        .WithMany("transaction")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Libarary.Models.Libarary_system.LibraryStaff", "LibraryStaff")
                        .WithMany("transaction")
                        .HasForeignKey("StuffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("LibraryMember");

                    b.Navigation("LibraryStaff");
                });

            modelBuilder.Entity("Libarary.Models.Books.Author", b =>
                {
                    b.Navigation("bookAuthor");
                });

            modelBuilder.Entity("Libarary.Models.Books.Book", b =>
                {
                    b.Navigation("bookAuthors");

                    b.Navigation("bookStorages");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("Libarary.Models.Books.Genre", b =>
                {
                    b.Navigation("book");
                });

            modelBuilder.Entity("Libarary.Models.Books.Publisher", b =>
                {
                    b.Navigation("book");
                });

            modelBuilder.Entity("Libarary.Models.Libarary_system.LibararyBranche", b =>
                {
                    b.Navigation("bookStorages");
                });

            modelBuilder.Entity("Libarary.Models.Libarary_system.LibraryMember", b =>
                {
                    b.Navigation("transaction");
                });

            modelBuilder.Entity("Libarary.Models.Libarary_system.LibraryStaff", b =>
                {
                    b.Navigation("transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
